const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const script=fs.readFileSync(__dirname+'/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
class Element{constructor(tag='div'){this.tag=tag;this.children=[];this.value='';this.dataset={};this.attributes={};this.listeners={};this.isConnected=true;this.classList={toggle(){}}}set textContent(v){this.text=String(v);this.children=[]}get textContent(){return this.text||''}append(...children){this.children.push(...children)}replaceChildren(...children){this.children=children}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,f){this.listeners[k]=f}focus(){this.focused=true}showModal(){this.open=true}close(){this.open=false;this.listeners.close?.()}get options(){return this.children}querySelector(){return this.children.find(x=>x.dataset.legacy)}remove(){}reset(){}}
function environment(initial){const ids={};for(const id of ['feedback','new','rows','empty','empty-title','empty-text','empty-action','count','search','form','company','role','status','note','editor','editor-title','save','form-feedback','close','cancel'])ids[id]=new Element();['待投递','已投递','面试中'].forEach(value=>{const el=new Element('option');el.value=value;ids.status.append(el)});ids.form.reset=()=>{['company','role','note'].forEach(k=>ids[k].value='');ids.status.value='待投递'};const filters=new Element();let value=initial,fail=false,writes=0;const storage={getItem(){return value},setItem(k,v){if(fail)throw Error('quota');value=v;writes++}};const ctx=vm.createContext({document:{getElementById:id=>ids[id],querySelector:()=>filters,createElement:t=>new Element(t)},localStorage:storage,crypto:{randomUUID:()=> 'new-id'},confirm:()=>true,console});vm.runInContext(script,ctx);return {ids,filters,ctx,storage,get value(){return value},get writes(){return writes},set fail(v){fail=v}}}
const fixture=[{id:'old-id',company:'保留公司',role:'产品经理',status:'已投递',note:'第一行\n第二行',extra:'keep'}];
const e=environment(JSON.stringify(fixture));assert.equal(e.ids.rows.children.length,1);assert.equal(e.writes,0);
e.ids.search.value='第二行';e.ids.search.oninput();assert.equal(e.ids.rows.children.length,1);e.ids.search.value='不匹配';e.ids.search.oninput();assert.equal(e.ids.rows.children.length,0);e.ids['empty-action'].onclick();assert.equal(e.ids.rows.children.length,1);
e.ids.new.onclick();e.ids.company.value='新增公司';e.ids.role.value='研发';e.ids.note.value='测试备注';e.ids.form.onsubmit({preventDefault(){}});let saved=JSON.parse(e.value);assert.equal(saved.length,2);assert.deepEqual(saved[0],fixture[0]);assert.equal(saved[1].company,'新增公司');assert.equal(e.ids.editor.open,false);
e.ids.rows.children[0].children[3].children[0].onclick();e.ids.note.value='修改后';e.ids.form.onsubmit({preventDefault(){}});saved=JSON.parse(e.value);assert.equal(saved[0].id,'old-id');assert.equal(saved[0].extra,'keep');assert.equal(saved[0].note,'修改后');
const reload=environment(e.value);assert.equal(reload.ids.rows.children.length,2);
e.ids.new.onclick();e.ids.company.value='不能保存';e.ids.role.value='岗位';e.fail=true;const old=e.value;e.ids.form.onsubmit({preventDefault(){}});assert.equal(e.value,old);assert.equal(e.ids.company.value,'不能保存');assert.equal(e.ids.editor.open,true);assert.match(e.ids['form-feedback'].textContent,/保存失败/);assert.equal(e.ids.save.disabled,false);
e.fail=false;e.ids.company.value='   ';e.ids.form.onsubmit({preventDefault(){}});assert.equal(e.value,old);assert.match(e.ids['form-feedback'].textContent,/不能为空/);
const corrupt=environment('{broken');assert.equal(corrupt.ids.new.disabled,true);assert.equal(corrupt.value,'{broken');assert.equal(corrupt.writes,0);
console.log('PASS 8 scenario groups: legacy preservation; search and clear; create; edit and extra fields; reload; save failure retention; whitespace validation; corrupt-storage protection.');
console.log('Evidence level: isolated JavaScript runtime with DOM/storage doubles; not browser or visual verification.');
e.ids.editor.querySelectorAll=()=>[e.ids.close,e.ids.company,e.ids.role,e.ids.status,e.ids.note,e.ids.cancel,e.ids.save];
let prevented=false;e.ctx.document.activeElement=e.ids.save;e.ids.editor.listeners.keydown({key:'Tab',shiftKey:false,preventDefault(){prevented=true}});assert.equal(prevented,true);assert.equal(e.ids.close.focused,true);
prevented=false;e.ctx.document.activeElement=e.ids.close;e.ids.editor.listeners.keydown({key:'Tab',shiftKey:true,preventDefault(){prevented=true}});assert.equal(prevented,true);assert.equal(e.ids.save.focused,true);
console.log('PASS explicit modal Tab and Shift+Tab boundary handling in isolated runtime.');
